### ISSUE TITLE
Pining packages in requirements.txt 

### ISSUE THREAD

**Issue by lerdem** [Nenirey/simplebot_tg#4]
Can you pin dependencies versions? I will reduce unexpected behavior for program.

**Comment by Nenirey** [comment]
i only pin deltchat dependecie because i never have problem with other libs, i use a telethon fork waiting for the new official release, for others i use the last github master, i you have problem with old libs please feed back here.

**Comment by lerdem** [comment]
I don't have problems with installation because i can't install without docs. After installing i'll give feedback.

**Comment by Nenirey** [comment]
Done!
