### ISSUE TITLE
Heroku no se conecta a GitHub

### ISSUE THREAD

**Issue by guillermo9108t** [Nenirey/simplebot_tg#5]
Últimamente no permite conectar GitHub a heroku, cuando le doy vincular me pone error crítico, he probado en todas las cuentas y es igual. Alguien sabe de este problema.

**Comment by Nenirey** [comment]
https://status.heroku.com/incidents/2413

**Comment by guillermo9108t** [comment]
> https://status.heroku.com/incidents/2413

Si, ahora entiendo. Espero que no sea para siempre, me conecto mas por el bot telegram Bridge que por el mismo telegram, lastima que no tengo un buen tutorial para montarlo en Railway.app

**Comment by guillermo9108t** [comment]
Por cierto muchas felicidades, as echo unos de los mejores bots, por lo menos para los cubanos es el #1

**Comment by guillermo9108t** [comment]
Me gustaría que este bot también funcionara para otros clientes de correo.
