### ISSUE TITLE
Error with loadings delta chats in auto

### ISSUE THREAD

**Issue by raymand211092** [Nenirey/simplebot_tg#7]
Error loading delta chats of [correo@redacted]
(<class 'telethon.errors.rpcerrorlist.UserDeactivatedError'>, UserDeactivatedError('The user has been deleted/deactivated (caused by GetDialogsRequest)'), <traceback object at 0x7f8dd15481c0>)

**Comment by Nenirey** [comment]
this is cause by the user chat deleted, banned or block you

**Comment by raymand211092** [comment]
Interesting..i'll keep following the logs!!
Thanks
